fix(pcapng): Timestamp resolution handling
The EnhancedPacketBlock have a variable timestamp resolution defined in the corresponding InterfaceDescriptionBlock.
This commit add support for the timestamp resolution.
If no timestamp resolution is set, default to micro-seconds.

ADD
 - EnhancedPacket timestamp resolution support (read and write)
 - TsResolution struct
 - Block::as_****_block() function (borrowed counterparts to Block::into_***_block() functions)

BREAKING CHANGE

PcapError: Add variants
EnhancedPacketBlock: Add field